name: Metrics
on:
  # Atualiza as 00:00 todos os dias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser testar agora
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configurações Visuais
          user: victorturques
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin: Linguagens (A barra colorida)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          
          # Plugin: Calendário Isométrico (Aquele 3D bonito)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
